### PR TITLE
Merge bulk migrated issues

### PR DESCRIPTION
**Pull request by strogonoff**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Would be awesome to merge this :wink:

**Comment by strogonoff** [comment]
> Would be awesome to merge this 😉

I’m going to build locally first and fix publication ID first before pushing to production branch.

**Comment by ronaldtse** [comment]
Ping @strogonoff can we merge these soon? Thanks!

**Comment by strogonoff** [comment]
Merging now & watching for any build issues

**Pull request merged**
